services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: pet-app-rabbitmq
    restart: always
    networks:
      - pet-community-network
    ports:
      - "5672:5672"# RabbitMQ 서버 포트
      - "15672:15672"# 관리 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10

  debezium:
    env_file: # 환경변수 파일을 사용하여 설정값을 관리할 수 있도록 env_file 옵션 추가
      - .env
    image: quay.io/debezium/server:3.4
    container_name: pet-app-debezium
    restart: always
    networks:
      - pet-community-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./debezium/config:/debezium/config
      - ./debezium/data:/debezium/data

networks:
  pet-community-network:
    external: true

volumes:
  rabbitmq-data:


