services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - pet-community-network
    ports:
      - "5672:5672"# RabbitMQ 서버 포트
      - "15672:15672"# 관리 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10

  debezium:
    environment:
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-test}
      DEBEZIUM_USER: ${DEBEZIUM_USER:-debezium}
      DEBEZIUM_PASSWORD: ${DEBEZIUM_PASSWORD:-debezium1234}
      DEBEZIUM_SOURCE_DATABASE_SERVER_ID: ${DEBEZIUM_SOURCE_DATABASE_SERVER_ID:-12345}
    image: quay.io/debezium/server:3.4
    networks:
      - pet-community-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./debezium/config:/debezium/config
      - ./debezium/data:/debezium/data

networks:
  pet-community-network:
    external: true

volumes:
  rabbitmq-data:

