spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_EMAIL:email}
    password: ${SMTP_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        prefetch: 10
        acknowledge-mode: auto
        concurrency: 4
        max-concurrency: 8
    publisher-confirm-type: correlated #해당 메시지 전송 확인
    requested-heartbeat: 30

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.elasticsearch.client: TRACE

mail:
  provider: smtp

server:
  address: 0.0.0.0
  port: 8081
