debezium.sink.type=rabbitmq
debezium.sink.rabbitmq.connection.host=rabbitmq
debezium.sink.rabbitmq.connection.port=${RABBITMQ_PORT}
debezium.sink.rabbitmq.connection.username=${RABBITMQ_USERNAME}
debezium.sink.rabbitmq.connection.password=${RABBITMQ_PASSWORD}
debezium.sink.rabbitmq.exchange=ex.main
#key 값을 라우팅 키로 설정
debezium.sink.rabbitmq.routingKey.source=key
# converter
#schema 없이 단순 문자열로 key를 전달하기 위한 설정
debezium.format.key=simplestring
debezium.source.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.source.value.converter.schemas.enable=false
#debezium이 제공하는 확장 헤더 기능을 비활성화, 확장 헤더는 이벤트에 추가적인 메타데이터를 포함하지만 필요없어서 용량 줄임
debezium.source.extended.headers.enabled=false
# smt
#outbox라는 이름으로 smt 설정
debezium.source.transforms=outbox
#공식 outbox smt 사용
debezium.source.transforms.outbox.type=io.debezium.transforms.outbox.EventRouter
#id 필드를 이벤트 id로 지정
debezium.source.transforms.outbox.table.field.event.id=id
#routingKey 필드를 이벤트 키로 지정
debezium.source.transforms.outbox.table.field.event.key=routing_key
#실제 전달해야 할 데이터
debezium.source.transforms.outbox.table.field.event.payload=payload
#라우팅 키로 사용할 필드 지정
debezium.source.transforms.outbox.route.by.field=routing_key
#id필드 추가(envlope: 부가 정보를 추가)
debezium.source.transforms.outbox.table.fields.additional.placement=id:envelope
#오프셋 정보를 파일로 저장하기 위한 설정
debezium.source.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
#오프셋 정보를 저장할 파일 경로
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
# mysql
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.database.hostname=${MYSQL_HOST}
debezium.source.database.port=${MYSQL_PORT}
debezium.source.database.user=${DEBEZIUM_USER}
debezium.source.database.password=${DEBEZIUM_PASSWORD}
debezium.source.database.server.id=${DEBEZIUM_SOURCE_DATABASE_SERVER_ID}
#모니터링할 테이블 설정, outbox_event 테이블의 변경사항을 모니터링
debezium.source.table.include.list=${MYSQL_DATABASE}.outbox_event
#토픽 접두사 설정
debezium.source.topic.prefix=outbox
#배치 사이즈 설정, 한번에 최대 1000개의 이벤트를 처리(기본값은 2048)
debezium.source.max.batch.size=1000
#0.5초마다
debezium.source.poll.interval.ms=500
#에러 발생 시 debeizium 서버 중단
debezium.source.event.processing.failure.handling.mode=fail
#스키마 변경 이력을 파일로 저장하기 위한 설정
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
#스키마 변경 이력을 저장할 파일 경로
debezium.source.schema.history.internal.file.filename=/debezium/data/history.dat
#스키마 히스토리 전체 테이블 변경 내역이 아닌 해당 테이블만 변경 내역 저장하는 설정
debezium.source.schema.history.internal.store.only.captured.tables.ddl=true
#스키마 변경 이벤트를 토픽에 포함하지 않도록 설정, 스키마 변경 이벤트는 일반적으로 필요하지 않으므로 false로 설정하여 불필요한 이벤트 생성을 방지
debezium.source.include.schema.changes=false
#스냅샷
debezium.source.snapshot.mode=initial
